
services:
  mysql:
    container_name: mysql
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ruser
      MYSQL_PASSWORD: rpassword
    ports:
      - "3307:3306"
    networks:
      - e-com-network
    volumes:
      - mysql-data:/var/lib/mysql

  ecommerce-api:
    container_name: ecommerce-api
    image: ecommerce:1.0.0
    ports:
      - "8080:8080"
    networks:
      - e-com-network
    depends_on:
      - mysql

networks:
  e-com-network:
    driver: bridge

volumes:
  mysql-data:
